"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, BadgeCheck, Building2, Check, ChevronDown, ExternalLink, FileText, LoaderCircle, RefreshCw, Search, ShieldCheck, ThumbsDown, UserPlus, Users } from "lucide-react";
import type { ContactIntelligenceView } from "@/lib/contacts/types";

const stateStyle = {
  VERIFIED: "bg-[#0C241C] text-[#34D399]",
  LIKELY_CURRENT: "bg-[#10283A] text-[#7DD3FC]",
  STALE_OR_UNCERTAIN: "bg-[#1C1708] text-[#FBBF24]",
  UNVERIFIED: "bg-[#101828] text-[#93A0B5]"
} as const;

export function ContactIntelligenceWorkspace({ jobId, jobTitle, companyName, projectId, initial }: { jobId: string; jobTitle: string; companyName: string; projectId: string | null; initial: ContactIntelligenceView }) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [manualOpen, setManualOpen] = useState(false);
  const providerReady = Boolean(initial.providerConfiguration.people);
  const approved = initial.contacts.find((contact) => contact.approvalState === "APPROVED") ?? null;
  const shortlist = initial.contacts.filter((contact) => contact.approvalState !== "APPROVED" && contact.approvalState !== "REJECTED");
  const rejected = initial.contacts.filter((contact) => contact.approvalState === "REJECTED");

  async function action(body: Record<string, unknown>, label: string) {
    setBusy(label); setError(null); setNotice(null);
    try {
      const response = await fetch(`/api/jobs/${jobId}/contacts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const payload = await response.json() as { error?: string; discovered?: number };
      if (!response.ok) throw new Error(payload.error ?? "Hiring-intelligence request failed.");
      setNotice(label === "approve" ? "Person approved for this job." : label === "reject" ? "Person rejected. You may select another candidate." : label === "manual" ? "Manual person saved as unverified owner-entered evidence." : `Research completed with ${payload.discovered ?? 0} relevant people.`);
      router.refresh();
      return true;
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Hiring-intelligence request failed.");
      router.refresh();
      return false;
    } finally { setBusy(null); }
  }

  async function submitManual(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formElement = event.currentTarget;
    const form = new FormData(formElement);
    const saved = await action({ action: "MANUAL_ADD", fullName: form.get("fullName"), currentTitle: form.get("currentTitle"), department: form.get("department"), seniority: form.get("seniority"), location: form.get("location"), professionalProfileUrl: form.get("professionalProfileUrl"), evidenceUrl: form.get("evidenceUrl"), projectId }, "manual");
    if (saved) { formElement.reset(); setManualOpen(false); }
  }

  function PersonCard({ contact, primary = false }: { contact: ContactIntelligenceView["contacts"][number]; primary?: boolean }) {
    const stale = contact.status === "STALE" || contact.verificationState === "STALE_OR_UNCERTAIN" || contact.approvalState === "STALE";
    return <article className={`min-w-0 rounded-[2rem] border bg-[#101828] p-5 shadow-[0_14px_42px_rgba(0,0,0,.06)] sm:p-6 ${primary ? "border-[#22D3EE] ring-2 ring-[#22D3EE]/10" : "border-[#1C283C]"}`}>
      <div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#22D3EE]">{contact.recommendationLabel}</p><h3 className="mt-2 break-words text-2xl font-semibold text-[#F4F7FB]">{contact.fullName}</h3><p className="mt-1 break-words text-sm font-semibold text-[#93A0B5]">{contact.currentTitle}</p><p className="mt-1 break-words text-sm text-[#93A0B5]">{contact.companyName}{contact.location ? ` · ${contact.location}` : ""}</p></div><span className="w-fit shrink-0 rounded-2xl bg-[#0E1C33] px-3 py-2 text-sm font-semibold text-white">{contact.relevanceScore}/100</span></div>
      <div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${stateStyle[contact.verificationState]}`}>{contact.verificationState.replaceAll("_", " ")}</span><span className="rounded-full bg-[#122033] px-2.5 py-1 text-[11px] font-semibold text-[#67E8F9]">{contact.relevanceLevel} RELEVANCE</span><span className="rounded-full bg-[#101828] px-2.5 py-1 text-[11px] font-semibold text-[#93A0B5]">{contact.approvalState}</span></div>
      {stale && <p className="mt-4 flex items-start gap-2 rounded-2xl bg-[#1C1708] p-3 text-xs leading-5 text-[#FBBF24]"><AlertTriangle className="mt-0.5 size-4 shrink-0" />This record is stale or uncertain. Reverify before relying on it.</p>}
      <div className="mt-5"><h4 className="text-sm font-semibold text-[#F4F7FB]">Why KYM Mail selected this person</h4><ul className="mt-2 space-y-1.5 text-xs leading-5 text-[#93A0B5]">{contact.relevanceReasons.map((reason) => <li key={reason} className="flex gap-2"><BadgeCheck className="mt-0.5 size-3.5 shrink-0 text-[#22D3EE]" />{reason}</li>)}</ul></div>
      <details className="mt-4 rounded-2xl bg-[#122033] p-3"><summary className="flex cursor-pointer items-center gap-2 text-xs font-semibold text-[#F4F7FB]"><ChevronDown className="size-3.5" /> Identity, role, and organization evidence</summary><div className="mt-3 space-y-2">{contact.sources.length ? contact.sources.map((source) => <p key={source.id} className="break-words text-xs leading-5 text-[#93A0B5]"><strong className="text-[#F4F7FB]">{source.fieldName.replaceAll("_", " ")}:</strong> {source.claimSummary}<br />{source.sourceType.replaceAll("_", " ")} · {source.providerKey} · confidence {source.confidence}{source.sourceUrl && <> · <a href={source.sourceUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-[#67E8F9]">View evidence <ExternalLink className="size-3" /></a></>}</p>) : <p className="text-xs text-[#93A0B5]">No independent provider evidence has been stored.</p>}</div></details>
      {contact.approvalState === "APPROVED" ? <p className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#0C241C] px-4 py-2 text-sm font-semibold text-[#34D399]"><ShieldCheck className="size-4" /> Approved {contact.approvedAt ? new Date(contact.approvedAt).toLocaleDateString() : ""}</p> : <div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => void action({ action: "APPROVE", contactId: contact.id }, "approve")} disabled={Boolean(busy) || stale} className="inline-flex min-h-11 items-center gap-2 rounded-full kym-action px-4 text-sm font-semibold text-white disabled:bg-[#0E1C33]"><Check className="size-4" /> Approve Person</button><button type="button" onClick={() => void action({ action: "REJECT", contactId: contact.id }, "reject")} disabled={Boolean(busy)} className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#1C283C] px-4 text-sm font-semibold text-[#93A0B5]"><ThumbsDown className="size-4" /> Reject</button></div>}
    </article>;
  }

  return <div className="mt-7 space-y-6">
    <section className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(260px,.65fr)]"><div className="min-w-0 rounded-[2rem] border border-[#1C283C] bg-[#101828] p-5 shadow-[0_20px_60px_rgba(0,0,0,.08)] sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#22D3EE]">Posting context</p><h2 className="mt-2 flex items-center gap-2 break-words text-2xl font-semibold text-[#F4F7FB]"><Building2 className="size-5 shrink-0 text-[#22D3EE]" />{initial.organization?.canonicalName ?? companyName}</h2></div><span className="w-fit rounded-full bg-[#122033] px-3 py-1.5 text-xs font-semibold text-[#67E8F9]">{initial.search?.postingType.replaceAll("_", " ") ?? "NOT CLASSIFIED"}</span></div>
      <p className="mt-4 text-sm leading-6 text-[#93A0B5]">Research uses the saved job, posting source, and organization evidence to rank relevant people for <strong>{jobTitle}</strong>. Relevance does not prove that a person is the hiring manager.</p>
      {initial.search?.postingTypeReasons.map((reason) => <p key={reason} className="mt-3 text-xs leading-5 text-[#93A0B5]">{reason}</p>)}
      {initial.search?.privateEquityContext && <div className="mt-4 rounded-2xl bg-[#101828] p-4 text-xs leading-5 text-[#93A0B5]"><p className="font-semibold text-[#F4F7FB]">Source-backed private-equity context: {initial.search.privateEquityContext.sponsorName}</p>{initial.search.privateEquityContext.evidence.map((item) => <p key={`${item.label}-${item.value}`} className="mt-1">{item.label}: {item.value}</p>)}</div>}
      {!providerReady && <p className="mt-5 flex items-start gap-2 rounded-2xl bg-[#122033] p-4 text-sm leading-6 text-[#67E8F9]"><AlertTriangle className="mt-0.5 size-4 shrink-0" />{initial.providerConfiguration.requirement} KYM Mail will not create sample people.</p>}
      {initial.search?.failureMessage && <p className="mt-4 rounded-2xl bg-[#122033] p-4 text-sm text-[#67E8F9]">{initial.search.failureMessage}</p>}
      {notice && <p className="mt-4 flex items-center gap-2 rounded-2xl bg-[#0C241C] p-3 text-sm text-[#34D399]"><Check className="size-4" />{notice}</p>}{error && <p role="alert" className="mt-4 rounded-2xl bg-[#122033] p-3 text-sm text-[#67E8F9]">{error}</p>}
      <div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => void action({ action: initial.search ? "REFRESH" : "SEARCH", projectId }, "search")} disabled={Boolean(busy) || !providerReady} className="inline-flex min-h-12 items-center gap-2 rounded-full kym-action px-5 py-3 text-sm font-semibold text-white disabled:bg-[#0E1C33]">{busy === "search" ? <LoaderCircle className="size-4 animate-spin" /> : initial.search ? <RefreshCw className="size-4" /> : <Search className="size-4" />}{initial.search ? "Refresh Research" : "Find Relevant Contact"}</button><button type="button" onClick={() => setManualOpen((value) => !value)} className="inline-flex min-h-12 items-center gap-2 rounded-full border border-[#22D3EE] px-5 py-3 text-sm font-semibold text-[#67E8F9]"><UserPlus className="size-4" /> Add Person Manually</button></div>
    </div><aside className="min-w-0 rounded-[2rem] border border-[#1C283C] bg-[#101828] p-5 shadow-[0_14px_42px_rgba(0,0,0,.06)]"><h2 className="flex items-center gap-2 text-lg font-semibold text-[#F4F7FB]"><ShieldCheck className="size-5 text-[#22D3EE]" /> Research controls</h2><div className="mt-4 space-y-3 text-xs leading-5 text-[#93A0B5]"><p><strong className="text-[#F4F7FB]">People provider:</strong> {initial.providerConfiguration.people ?? "Not configured"}</p><p><strong className="text-[#F4F7FB]">Search state:</strong> {initial.search?.status.replaceAll("_", " ") ?? "Not searched"}</p><p><strong className="text-[#F4F7FB]">Cache:</strong> Results persist for {90} days; page refreshes do not rerun research.</p><p><strong className="text-[#F4F7FB]">Email intelligence:</strong> Disabled for Gate 8.</p></div>{initial.resumeContext && <div className="mt-5 rounded-2xl bg-[#122033] p-3 text-xs leading-5 text-[#93A0B5]"><p className="flex items-center gap-2 font-semibold text-[#F4F7FB]"><FileText className="size-4" /> Approved résumé context</p><p className="mt-1">Version {initial.resumeContext.versionNumber} · {initial.resumeContext.status}</p><p className="mt-1">Displayed for owner context only; research does not alter it.</p></div>}</aside></section>

    {manualOpen && <form onSubmit={submitManual} className="rounded-[2rem] border border-[#1C283C] bg-[#101828] p-5 shadow-[0_14px_42px_rgba(0,0,0,.06)] sm:p-7"><h2 className="text-xl font-semibold text-[#F4F7FB]">Add a professional person</h2><p className="mt-2 text-sm text-[#93A0B5]">The organization is locked to {initial.organization?.canonicalName ?? companyName}. Manual claims remain UNVERIFIED until supported by independent evidence.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#F4F7FB]">Full name *<input name="fullName" required minLength={2} maxLength={160} className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB]">Current title *<input name="currentTitle" required minLength={2} maxLength={200} className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB]">Department<input name="department" maxLength={120} className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB]">Seniority<input name="seniority" maxLength={80} className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB]">Location<input name="location" maxLength={200} className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB]">Professional profile URL<input name="professionalProfileUrl" type="url" placeholder="https://" className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label><label className="text-sm font-semibold text-[#F4F7FB] sm:col-span-2">Optional evidence URL<input name="evidenceUrl" type="url" placeholder="https://" className="mt-2 min-h-11 w-full rounded-xl border border-[#1C283C] bg-[#101828] px-3 font-normal text-[#93A0B5]" /></label></div><button type="submit" disabled={Boolean(busy)} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#0E1C33] px-5 py-3 text-sm font-semibold text-white disabled:bg-[#0E1C33]">{busy === "manual" ? <LoaderCircle className="size-4 animate-spin" /> : <Check className="size-4" />} Save Manual Person</button></form>}

    {approved && <section><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#22D3EE]">Approved contact</p><div className="mt-4"><PersonCard contact={approved} primary /></div></section>}
    <section><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#22D3EE]">{approved ? "Other people" : "Ranked shortlist"}</p><h2 className="mt-1 flex items-center gap-2 text-2xl font-semibold text-[#F4F7FB]"><Users className="size-6 text-[#22D3EE]" />{shortlist.length} candidate{shortlist.length === 1 ? "" : "s"}</h2></div><p className="text-xs text-[#93A0B5]">Verification and relevance are independent. Ranking is deterministic.</p></div>{shortlist.length === 0 ? <div className="mt-5 rounded-[2rem] border border-dashed border-[#1C283C] bg-[#101828] p-8 text-center"><Users className="mx-auto size-8 text-[#22D3EE]" /><h3 className="mt-3 text-xl font-semibold text-[#F4F7FB]">No relevant people found yet.</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#93A0B5]">Configure the listed provider access, retry after a provider outage, or add a real professional person manually. KYM Mail will not fabricate a result.</p></div> : <div className="mt-5 grid min-w-0 gap-5 lg:grid-cols-2">{shortlist.map((contact) => <PersonCard key={contact.id} contact={contact} />)}</div>}</section>
    {rejected.length > 0 && <details className="rounded-2xl border border-[#1C283C] bg-[#101828] p-4"><summary className="cursor-pointer text-sm font-semibold text-[#93A0B5]">Rejected people ({rejected.length})</summary><ul className="mt-3 space-y-2 text-sm text-[#93A0B5]">{rejected.map((contact) => <li key={contact.id}>{contact.fullName} · {contact.currentTitle}</li>)}</ul></details>}
  </div>;
}
