import { redirect } from "next/navigation";
import { BadgeCheck, BookOpenCheck, Building2, Database, FileSearch, GraduationCap, Layers3, MapPin, Sparkles } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { CareerAddFact } from "@/components/career-add-fact";
import { CareerFactEditor, type CareerEditorField } from "@/components/career-fact-editor";
import { CareerReviewQueue, type CareerReviewAuthoritativeFact, type CareerReviewCandidate } from "@/components/career-review-queue";
import { getOwnerContext } from "@/lib/auth/owner-context";

export const metadata = { title: "Master Career Profile" };

type Organization = { id: string; canonical_name: string };
type Title = { id: string; canonical_name: string };
type Experience = { id: string; canonical_key: string; organization_id: string; client_organization_id: string | null; title_id: string | null; start_date: string | null; start_precision: "MONTH" | "YEAR" | "UNKNOWN"; end_date: string | null; end_precision: "MONTH" | "YEAR" | "UNKNOWN"; is_current: boolean; location_text: string | null; summary: string | null; completeness: "COMPLETE" | "PARTIAL"; authority_status: string };
type Project = { id: string; canonical_key: string; canonical_name: string; project_kind: string; experience_id: string | null; client_organization_id: string | null; summary: string; business_challenge: string | null; architecture: string | null; impact: string | null; authority_status: string };
type Accomplishment = { id: string; experience_id: string | null; project_id: string | null; category: string; statement: string };
type Metric = { id: string; accomplishment_id: string; metric_type: string; value_numeric: number | null; value_text: string | null; before_numeric: number | null; before_text: string | null; after_numeric: number | null; after_text: string | null; unit: string | null; currency: string | null; qualifier: string | null; scope_text: string | null };
type SourceExtraction = { id: string; source_identity: "RESUME_A" | "RESUME_B"; candidate_count: number; extraction_method: string; extracted_at: string; career_sources: { label: string; content_sha256: string | null } | null };
type CareerFact = { id: string; entity_type: string; entity_id: string; field_name: string; fact_type: string; current_value: unknown; status: string; confirmation_method: string | null; version_number: number; first_added_at: string; last_changed_at: string };
type CareerFactVersion = { id: string; career_fact_id: string; version_number: number; previous_value: unknown; new_value: unknown; change_source: string; reason: string | null; changed_at: string };
type CareerFactSource = { id: string; career_fact_id: string; source_reference: string; confirmation_method: string; first_added_at: string; last_changed_at: string; career_sources: { label: string; intake_identity: string | null } | null };
type CareerProvenance = { id: string; entity_type: string; entity_id: string; field_name: string; source_page: number; source_wording: string; source_role: string; resolution_note: string | null; created_at: string; updated_at: string; career_sources: { label: string; intake_identity: string | null } | null };

const datePrecisionOptions = ["MONTH", "YEAR", "UNKNOWN"].map((value) => ({ label: value.charAt(0) + value.slice(1).toLowerCase(), value }));
const completenessOptions = ["COMPLETE", "PARTIAL"].map((value) => ({ label: value.charAt(0) + value.slice(1).toLowerCase(), value }));
const credentialStatusOptions = ["ACTIVE", "INACTIVE", "COMPLETED", "CANDIDATE"].map((value) => ({ label: value.charAt(0) + value.slice(1).toLowerCase(), value }));
const skillCategoryOptions = ["FINANCE", "ACCOUNTING", "TECHNOLOGY", "SYSTEM", "DATA", "LEADERSHIP", "INDUSTRY"].map((value) => ({ label: value.charAt(0) + value.slice(1).toLowerCase(), value }));
const accomplishmentCategoryOptions = ["FINANCE", "ACCOUNTING", "AUTOMATION", "CONTROLS", "LEADERSHIP", "REPORTING", "OPERATIONS", "TECHNOLOGY"].map((value) => ({ label: value.charAt(0) + value.slice(1).toLowerCase(), value }));

function formatCareerDate(value: string | null, precision: Experience["start_precision"], current = false) {
  if (current) return "Present";
  if (!value) return "Date not provided";
  return new Intl.DateTimeFormat("en-US", { ...(precision === "MONTH" ? { month: "short" as const } : {}), year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
}

function formatMetric(metric: Metric) {
  const format = (value: number | null, text: string | null) => value === null ? text : new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value);
  if (metric.before_numeric !== null || metric.before_text) return `${format(metric.before_numeric, metric.before_text)} → ${format(metric.after_numeric, metric.after_text)}`;
  const value = format(metric.value_numeric, metric.value_text);
  const unit = metric.unit ? ` ${metric.unit.toLowerCase().replaceAll("_", " ")}` : "";
  return `${metric.qualifier === "MINIMUM" ? "At least " : metric.qualifier === "UNDER" ? "Under " : ""}${value ?? ""}${unit}`;
}

export default async function CareerProfilePage() {
  const owner = await getOwnerContext();
  if (!owner?.user.email) redirect("/sign-in");
  const database = owner.database;
  const ownerId = owner.user.id;
  const [profileResult, organizationsResult, titlesResult, experiencesResult, educationResult, credentialsResult, skillsResult, projectsResult, accomplishmentsResult, metricsResult, aliasesResult, sourcesResult, provenanceResult, historyResult, extractionsResult, candidatesResult, factsResult, factVersionsResult, factSourcesResult] = await Promise.all([
    database.from("career_profiles").select("full_name, professional_headline, location_text, professional_summary, years_experience_claim, authority_status, updated_at").eq("owner_id", ownerId).maybeSingle(),
    database.from("career_organizations").select("id, canonical_name").eq("owner_id", ownerId),
    database.from("career_titles").select("id, canonical_name").eq("owner_id", ownerId),
    database.from("career_experiences").select("id, canonical_key, organization_id, client_organization_id, title_id, start_date, start_precision, end_date, end_precision, is_current, location_text, summary, completeness, authority_status").eq("owner_id", ownerId).order("start_date", { ascending: false, nullsFirst: false }),
    database.from("career_education").select("id, degree_name, field_of_study, institution_name, completed_on, authority_status").eq("owner_id", ownerId),
    database.from("career_credentials").select("id, credential_name, credential_status, issuing_organization, authority_status").eq("owner_id", ownerId),
    database.from("career_skills").select("id, canonical_name, category, authority_status").eq("owner_id", ownerId).order("canonical_name"),
    database.from("career_projects").select("id, canonical_key, canonical_name, project_kind, experience_id, client_organization_id, summary, business_challenge, architecture, impact, authority_status").eq("owner_id", ownerId).order("canonical_name"),
    database.from("career_accomplishments").select("id, experience_id, project_id, category, statement").eq("owner_id", ownerId),
    database.from("career_metrics").select("id, accomplishment_id, metric_type, value_numeric, value_text, before_numeric, before_text, after_numeric, after_text, unit, currency, qualifier, scope_text").eq("owner_id", ownerId),
    database.from("career_aliases").select("entity_type, entity_id, alias_text").eq("owner_id", ownerId),
    database.from("career_sources").select("id, label, authority_status").eq("owner_id", ownerId).order("reviewed_at"),
    database.from("career_provenance").select("id, entity_type, entity_id, field_name, source_page, source_wording, source_role, resolution_note, created_at, updated_at, career_sources(label, intake_identity)").eq("owner_id", ownerId).order("updated_at", { ascending: false }),
    database.from("career_fact_history").select("id, entity_type, changed_fields, change_source, changed_at").eq("owner_id", ownerId).order("changed_at", { ascending: false }).limit(5),
    database.from("career_source_extractions").select("id, source_identity, candidate_count, extraction_method, extracted_at, career_sources(label, content_sha256)").eq("owner_id", ownerId).eq("extraction_status", "SUCCEEDED").order("source_identity"),
    database.from("career_candidate_facts").select("id, group_key, entity_type, field_name, career_fact_id, normalized_claim, extracted_value, source_reference, classification, status, review_reason, career_sources(label, intake_identity)").eq("owner_id", ownerId).neq("status", "REJECTED").order("created_at"),
    database.from("career_facts").select("id, entity_type, entity_id, field_name, fact_type, current_value, status, confirmation_method, version_number, first_added_at, last_changed_at").eq("owner_id", ownerId).order("last_changed_at", { ascending: false }),
    database.from("career_fact_versions").select("id, career_fact_id, version_number, previous_value, new_value, change_source, reason, changed_at").eq("owner_id", ownerId).order("changed_at", { ascending: false }).limit(12),
    database.from("career_fact_sources").select("id, career_fact_id, source_reference, confirmation_method, first_added_at, last_changed_at, career_sources(label, intake_identity)").eq("owner_id", ownerId).order("last_changed_at", { ascending: false }),
  ]);
  const failed = [profileResult, organizationsResult, titlesResult, experiencesResult, educationResult, credentialsResult, skillsResult, projectsResult, accomplishmentsResult, metricsResult, aliasesResult, sourcesResult, provenanceResult, historyResult, extractionsResult, candidatesResult, factsResult, factVersionsResult, factSourcesResult].some((result) => result.error);
  if (failed) throw new Error("CAREER_PROFILE_UNAVAILABLE");
  if (!profileResult.data) throw new Error("CAREER_PROFILE_NOT_IMPORTED");

  const profile = profileResult.data;
  const organizations = (organizationsResult.data ?? []) as Organization[];
  const titles = (titlesResult.data ?? []) as Title[];
  const experiences = (experiencesResult.data ?? []) as Experience[];
  const projects = (projectsResult.data ?? []) as Project[];
  const accomplishments = (accomplishmentsResult.data ?? []) as Accomplishment[];
  const metrics = (metricsResult.data ?? []) as Metric[];
  const organizationNames = new Map(organizations.map((organization) => [organization.id, organization.canonical_name]));
  const titleNames = new Map(titles.map((title) => [title.id, title.canonical_name]));
  const aliases = aliasesResult.data ?? [];
  const skillsByCategory = Map.groupBy(skillsResult.data ?? [], (skill) => skill.category as string);
  const organizationOptions = organizations.map((item) => ({ label: item.canonical_name, value: item.id }));
  const titleOptions = titles.map((item) => ({ label: item.canonical_name, value: item.id }));
  const experienceOptions = experiences.map((item) => ({ label: `${titleNames.get(item.title_id ?? "") ?? "Earlier role"} · ${organizationNames.get(item.organization_id) ?? "Organization"}`, value: item.id }));
  const accomplishmentOptions = accomplishments.map((item) => ({ label: item.statement.slice(0, 90), value: item.id }));
  const extractions = (extractionsResult.data ?? []) as unknown as SourceExtraction[];
  const allCandidates = (candidatesResult.data ?? []) as unknown as CareerReviewCandidate[];
  const reviewGroupKeys = new Set(allCandidates.filter((candidate) => candidate.status === "NEEDS_REVIEW" || candidate.status === "CONFLICT").map((candidate) => candidate.group_key));
  const reviewCandidates = allCandidates.filter((candidate) => reviewGroupKeys.has(candidate.group_key));
  const facts = (factsResult.data ?? []) as CareerFact[];
  const factsById = new Map(facts.map((fact) => [fact.id, fact]));
  const factSources = (factSourcesResult.data ?? []) as unknown as CareerFactSource[];
  const factSourcesByFact = Map.groupBy(factSources, (source) => source.career_fact_id);
  const provenance = (provenanceResult.data ?? []) as unknown as CareerProvenance[];
  const autoConfirmedFacts = facts.filter((fact) => fact.confirmation_method === "AUTO_CONFIRMED_SOURCE_AGREEMENT");
  const ownerAddedFacts = facts.filter((fact) => fact.fact_type.startsWith("OWNER_") || (fact.current_value && typeof fact.current_value === "object" && "ownerConfirmedClaim" in fact.current_value));
  const factVersions = (factVersionsResult.data ?? []) as CareerFactVersion[];

  const displayFactValue = (value: unknown) => {
    if (typeof value === "string" || typeof value === "number") return String(value);
    if (value && typeof value === "object") {
      const record = value as Record<string, unknown>;
      if (typeof record.ownerConfirmedClaim === "string") return record.ownerConfirmedClaim;
      if (typeof record.sourceWording === "string") return record.sourceWording;
    }
    return JSON.stringify(value);
  };
  const authoritativeFacts = Array.from(new Map(reviewCandidates.flatMap((candidate) => {
    const fact = candidate.career_fact_id ? factsById.get(candidate.career_fact_id) : undefined;
    if (!fact) return [];
    const value: CareerReviewAuthoritativeFact = {
      groupKey: candidate.group_key,
      value: fact.current_value,
      confirmationMethod: fact.confirmation_method,
      sources: (factSourcesByFact.get(fact.id) ?? []).map((source) => ({ label: source.career_sources?.label ?? "Reviewed source", identity: source.career_sources?.intake_identity ?? null, reference: source.source_reference }))
    };
    return [[candidate.group_key, value] as const];
  })).values());

  return <AppShell email={owner.user.email} canSignOut={owner.mode === "authenticated"} active="career">
    <div className="mx-auto max-w-6xl">
      <header id="overview" className="rounded-[2rem] border border-[#E8E2E3] bg-[#FFFCFB] p-7 shadow-[0_18px_54px_rgba(24,58,90,.08)] sm:p-9">
        <div className="flex flex-wrap items-start justify-between gap-5">
          <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#D95B72]">Authoritative career data layer</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-[#183A5A] sm:text-5xl">{profile.full_name}</h1><p className="mt-3 text-lg font-semibold text-[#A73D52]">{profile.professional_headline}</p>{profile.location_text && <p className="mt-3 flex items-center gap-2 text-sm text-[#64748B]"><MapPin className="size-4 text-[#D95B72]" />{profile.location_text}</p>}</div>
          <div className="flex items-center gap-2"><CareerFactEditor entityType="profile" recordId={ownerId} title="Master Career Profile" fields={[
            { key: "full_name", label: "Professional name" }, { key: "professional_headline", label: "Headline" }, { key: "location_text", label: "Location" }, { key: "years_experience_claim", label: "Experience claim", placeholder: "23+" }, { key: "professional_summary", label: "Professional summary", kind: "textarea" }
          ]} initialValues={{ full_name: profile.full_name, professional_headline: profile.professional_headline, location_text: profile.location_text, years_experience_claim: profile.years_experience_claim, professional_summary: profile.professional_summary }} /><span className="inline-flex items-center gap-2 rounded-full bg-[#F7DDE1] px-4 py-2 text-xs font-semibold uppercase tracking-[.1em] text-[#A73D52]"><BadgeCheck className="size-4" /> Resolved profile</span></div>
        </div>
        <p className="mt-7 max-w-4xl text-sm leading-7 text-[#52657A]">{profile.professional_summary}</p>
        <div className="mt-7 grid gap-3 sm:grid-cols-4">
          {[{ label: "Experience", value: profile.years_experience_claim ?? "Verified", icon: Building2 }, { label: "Career records", value: experiences.length, icon: Layers3 }, { label: "Canonical projects", value: projects.length, icon: Sparkles }, { label: "Provenance facts", value: provenance.length, icon: Database }].map((stat) => <div key={stat.label} className="rounded-2xl bg-[#FFF3F4] p-4"><stat.icon className="size-4 text-[#D95B72]" /><p className="mt-3 text-2xl font-semibold text-[#183A5A]">{stat.value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.08em] text-[#64748B]">{stat.label}</p></div>)}
        </div>
        <nav aria-label="Career Profile sections" className="mt-6 flex gap-2 overflow-x-auto pb-1 text-xs font-semibold text-[#52657A]">{["Overview", "Experience", "Accomplishments", "Metrics", "Skills", "Technologies", "Education", "Credentials", "Applications / Projects", "Review Needed"].map((section) => <a key={section} href={`#${section.toLowerCase().replaceAll(" / ", "-").replaceAll(" ", "-")}`} className="shrink-0 rounded-full border border-[#E8E2E3] bg-white px-3 py-2 hover:border-[#D95B72] hover:text-[#A73D52]">{section}</a>)}</nav>
      </header>

      <section className="mt-8 rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-3"><FileSearch className="size-5 text-[#D95B72]" /><h2 className="text-xl font-semibold text-[#183A5A]">Source extraction & deterministic comparison</h2></div><p className="mt-2 max-w-3xl text-sm leading-6 text-[#64748B]">Each resume is extracted once and keyed by its source hash. Refreshing this page reads the persisted result; it does not run extraction or send career data to an AI provider.</p></div><CareerAddFact /></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2">{extractions.map((extraction) => <article key={extraction.id} className="rounded-2xl bg-[#FFF3F4] p-4"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#A73D52]">{extraction.source_identity.replace("RESUME_", "Resume ")}</p><p className="mt-2 font-semibold text-[#183A5A]">{extraction.career_sources?.label}</p><p className="mt-1 text-sm text-[#64748B]">{extraction.candidate_count} persisted candidate facts · {extraction.extraction_method.replaceAll("_", " ").toLowerCase()}</p><p className="mt-2 font-mono text-[10px] text-[#8A6A71]">SHA-256 {extraction.career_sources?.content_sha256?.slice(0, 12)}…</p></article>)}</div>
        <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#A73D52]">Safe auto-confirmed facts · {autoConfirmedFacts.length}</p>{autoConfirmedFacts.length > 0 ? <div className="mt-3 flex flex-wrap gap-2">{autoConfirmedFacts.slice(0, 24).map((fact) => <span key={fact.id} className="rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-800">{displayFactValue(fact.current_value)} · both sources</span>)}</div> : <p className="mt-2 text-sm text-[#64748B]">No low-risk exact agreements were eligible for automatic confirmation.</p>}</div>
        {ownerAddedFacts.length > 0 && <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-[.1em] text-[#A73D52]">Owner-added authoritative facts</p><ul className="mt-3 grid gap-2 sm:grid-cols-2">{ownerAddedFacts.map((fact) => <li key={fact.id} className="rounded-2xl border border-[#E8E2E3] px-4 py-3 text-sm text-[#52657A]">{displayFactValue(fact.current_value)}</li>)}</ul></div>}
      </section>

      <section id="review-needed" className="mt-8"><div className="mb-4 flex items-center gap-3"><BadgeCheck className="size-5 text-[#D95B72]" /><div><h2 className="text-2xl font-semibold tracking-[-.03em] text-[#183A5A]">Review Needed</h2><p className="mt-1 text-sm text-[#64748B]">Only conflicts, ambiguous facts, and unique source claims appear here.</p></div></div><CareerReviewQueue candidates={reviewCandidates} authoritativeFacts={authoritativeFacts} /></section>

      <section id="experience" className="mt-8"><div className="flex items-center gap-3"><Building2 className="size-5 text-[#D95B72]" /><h2 className="text-2xl font-semibold tracking-[-.03em] text-[#183A5A]">Experience</h2></div><div className="mt-4 space-y-4">{experiences.map((experience) => <article key={experience.id} className="rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6 shadow-[0_12px_36px_rgba(24,58,90,.05)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-[#183A5A]">{experience.title_id ? titleNames.get(experience.title_id) : "Earlier finance/accounting leadership"}</h3><p className="mt-1 text-sm font-semibold text-[#A73D52]">{organizationNames.get(experience.organization_id)}{experience.client_organization_id ? ` · Client: ${organizationNames.get(experience.client_organization_id)}` : ""}</p></div><div className="flex items-center gap-3"><p className="text-sm font-semibold text-[#64748B]">{formatCareerDate(experience.start_date, experience.start_precision)} — {formatCareerDate(experience.end_date, experience.end_precision, experience.is_current)}</p><CareerFactEditor compact entityType="experience" recordId={experience.id} title={titleNames.get(experience.title_id ?? "") ?? "Earlier career record"} fields={[
              { key: "organization_id", label: "Employer", kind: "select", options: organizationOptions }, { key: "client_organization_id", label: "Client", kind: "select", options: organizationOptions }, { key: "title_id", label: "Title", kind: "select", options: titleOptions }, { key: "start_date", label: "Start date", kind: "date" }, { key: "start_precision", label: "Start precision", kind: "select", options: datePrecisionOptions }, { key: "end_date", label: "End date", kind: "date" }, { key: "end_precision", label: "End precision", kind: "select", options: datePrecisionOptions }, { key: "is_current", label: "This is a current role", kind: "checkbox" }, { key: "location_text", label: "Location" }, { key: "completeness", label: "Record completeness", kind: "select", options: completenessOptions }, { key: "summary", label: "Role summary", kind: "textarea" }
            ]} initialValues={{ organization_id: experience.organization_id, client_organization_id: experience.client_organization_id, title_id: experience.title_id, start_date: experience.start_date, start_precision: experience.start_precision, end_date: experience.end_date, end_precision: experience.end_precision, is_current: experience.is_current, location_text: experience.location_text, completeness: experience.completeness, summary: experience.summary }} /></div></div>{experience.summary && <p className="mt-4 text-sm leading-6 text-[#64748B]">{experience.summary}</p>}<ul className="mt-4 grid gap-2 md:grid-cols-2">{accomplishments.filter((value) => value.experience_id === experience.id).map((value) => <li key={value.id} className="flex gap-2 text-sm leading-6 text-[#52657A]"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#D95B72]" /><span className="grow">{value.statement}</span><CareerFactEditor compact entityType="accomplishment" recordId={value.id} title="Accomplishment" fields={[{ key: "category", label: "Category", kind: "select", options: accomplishmentCategoryOptions }, { key: "statement", label: "Evidence statement", kind: "textarea" }]} initialValues={{ category: value.category, statement: value.statement }} /></li>)}</ul>{experience.completeness === "PARTIAL" && <p className="mt-4 text-xs font-semibold uppercase tracking-[.08em] text-[#8A6A71]">Source-limited partial record · no dates or title inferred</p>}</article>)}</div></section>

      <section id="accomplishments" className="mt-8"><div className="flex items-center gap-3"><BadgeCheck className="size-5 text-[#D95B72]" /><h2 className="text-2xl font-semibold tracking-[-.03em] text-[#183A5A]">Accomplishments</h2></div><div className="mt-4 grid gap-3 md:grid-cols-2">{accomplishments.map((item) => <article key={item.id} className="flex items-start gap-3 rounded-2xl border border-[#E8E2E3] bg-[#FFFCFB] p-4"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#D95B72]" /><p className="grow text-sm leading-6 text-[#52657A]">{item.statement}</p><CareerFactEditor compact entityType="accomplishment" recordId={item.id} title="Accomplishment" fields={[{ key: "category", label: "Category", kind: "select", options: accomplishmentCategoryOptions }, { key: "statement", label: "Evidence statement", kind: "textarea" }]} initialValues={{ category: item.category, statement: item.statement }} /></article>)}</div></section>

      <section id="applications-projects" className="mt-8"><div className="flex items-center gap-3"><Sparkles className="size-5 text-[#D95B72]" /><h2 className="text-2xl font-semibold tracking-[-.03em] text-[#183A5A]">Applications / Projects</h2></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{projects.map((project) => { const projectAliases = aliases.filter((alias) => alias.entity_type === "PROJECT" && alias.entity_id === project.id); return <article key={project.id} className="rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-semibold text-[#183A5A]">{project.canonical_name}</h3><div className="flex items-center gap-2"><span className="rounded-full bg-[#F7DDE1] px-3 py-1 text-[10px] font-semibold uppercase tracking-[.08em] text-[#A73D52]">{project.project_kind.replaceAll("_", " ")}</span><CareerFactEditor compact entityType="project" recordId={project.id} title={project.canonical_name} fields={[{ key: "canonical_name", label: "Canonical name" }, { key: "experience_id", label: "Related career record", kind: "select", options: experienceOptions }, { key: "client_organization_id", label: "Client", kind: "select", options: organizationOptions }, { key: "summary", label: "Summary", kind: "textarea" }, { key: "business_challenge", label: "Business challenge", kind: "textarea" }, { key: "architecture", label: "Architecture", kind: "textarea" }, { key: "impact", label: "Impact", kind: "textarea" }]} initialValues={{ canonical_name: project.canonical_name, experience_id: project.experience_id, client_organization_id: project.client_organization_id, summary: project.summary, business_challenge: project.business_challenge, architecture: project.architecture, impact: project.impact }} /></div></div>{projectAliases.length > 0 && <p className="mt-2 text-xs text-[#64748B]">Also sourced as: {projectAliases.map((alias) => alias.alias_text).join(", ")}</p>}<p className="mt-4 text-sm leading-6 text-[#64748B]">{project.summary}</p>{project.impact && <p className="mt-4 rounded-2xl bg-[#FFF3F4] p-4 text-sm leading-6 text-[#52657A]"><span className="font-semibold text-[#A73D52]">Impact: </span>{project.impact}</p>}<ul className="mt-4 space-y-2">{accomplishments.filter((value) => value.project_id === project.id).map((value) => <li key={value.id} className="flex items-start gap-2 text-sm text-[#52657A]"><span className="grow">{value.statement}</span><CareerFactEditor compact entityType="accomplishment" recordId={value.id} title="Project accomplishment" fields={[{ key: "category", label: "Category", kind: "select", options: accomplishmentCategoryOptions }, { key: "statement", label: "Evidence statement", kind: "textarea" }]} initialValues={{ category: value.category, statement: value.statement }} /></li>)}</ul></article>; })}</div></section>

      <div className="mt-8 grid gap-6 lg:grid-cols-2">
        <section id="skills" className="rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6"><div className="flex items-center gap-3"><BookOpenCheck className="size-5 text-[#D95B72]" /><h2 className="text-xl font-semibold text-[#183A5A]">Skills</h2></div><span id="technologies" className="block scroll-mt-6" /><p className="mt-2 text-sm text-[#64748B]">Supported capabilities and technologies; no proficiency level is inferred.</p><div className="mt-5 space-y-5">{Array.from(skillsByCategory.entries()).map(([category, skills]) => <div key={category}><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#A73D52]">{category === "TECHNOLOGY" || category === "SYSTEM" || category === "DATA" ? `${category} technologies` : category}</p><div className="mt-2 flex flex-wrap gap-2">{skills.map((skill) => <span key={skill.id} className="inline-flex items-center gap-1 rounded-full border border-[#E8E2E3] bg-[#FFF3F4]/60 py-1 pl-3 pr-1 text-xs font-semibold text-[#52657A]">{skill.canonical_name}<CareerFactEditor compact entityType="skill" recordId={skill.id} title={skill.canonical_name} fields={[{ key: "canonical_name", label: "Skill name" }, { key: "category", label: "Category", kind: "select", options: skillCategoryOptions }]} initialValues={{ canonical_name: skill.canonical_name, category: skill.category }} /></span>)}</div></div>)}</div></section>
        <div className="space-y-6"><section id="education" className="rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6"><div className="flex items-center gap-3"><GraduationCap className="size-5 text-[#D95B72]" /><h2 className="text-xl font-semibold text-[#183A5A]">Education</h2></div><div className="mt-5 space-y-4">{(educationResult.data ?? []).map((item) => <div key={item.id} className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#183A5A]">{item.degree_name}{item.field_of_study ? ` in ${item.field_of_study}` : ""}</p><p className="mt-1 text-sm text-[#64748B]">{item.institution_name}</p></div><CareerFactEditor compact entityType="education" recordId={item.id} title={item.degree_name} fields={[{ key: "degree_name", label: "Degree" }, { key: "field_of_study", label: "Field of study" }, { key: "institution_name", label: "Institution" }, { key: "completed_on", label: "Completion date", kind: "date" }]} initialValues={{ degree_name: item.degree_name, field_of_study: item.field_of_study, institution_name: item.institution_name, completed_on: item.completed_on }} /></div>)}</div><div id="credentials" className="mt-6 border-t border-[#E8E2E3] pt-5"><h3 className="font-semibold text-[#183A5A]">Credentials</h3><div className="mt-3 space-y-3">{(credentialsResult.data ?? []).map((item) => <div key={item.id} className="flex items-start justify-between gap-3 rounded-2xl bg-[#FFF3F4] p-4"><div><p className="font-semibold text-[#183A5A]">{item.credential_name}</p><p className="mt-1 text-xs font-semibold uppercase tracking-[.1em] text-[#A73D52]">{item.credential_status}</p></div><CareerFactEditor compact entityType="credential" recordId={item.id} title={item.credential_name} fields={[{ key: "credential_name", label: "Credential" }, { key: "credential_status", label: "Status", kind: "select", options: credentialStatusOptions }, { key: "issuing_organization", label: "Issuing organization" }]} initialValues={{ credential_name: item.credential_name, credential_status: item.credential_status, issuing_organization: item.issuing_organization }} /></div>)}</div></div></section>
          <section id="metrics" className="rounded-3xl border border-[#E8E2E3] bg-[#FFFCFB] p-6"><div className="flex items-center gap-3"><Database className="size-5 text-[#D95B72]" /><h2 className="text-xl font-semibold text-[#183A5A]">Metrics</h2></div><div className="mt-5 space-y-3">{metrics.map((metric) => { const accomplishment = accomplishments.find((value) => value.id === metric.accomplishment_id); const metricFields: CareerEditorField[] = [{ key: "accomplishment_id", label: "Evidence statement", kind: "select", options: accomplishmentOptions }, { key: "metric_type", label: "Metric type" }, { key: "value_numeric", label: "Value", kind: "number" }, { key: "value_text", label: "Value text" }, { key: "before_numeric", label: "Before", kind: "number" }, { key: "before_text", label: "Before text" }, { key: "after_numeric", label: "After", kind: "number" }, { key: "after_text", label: "After text" }, { key: "unit", label: "Unit" }, { key: "currency", label: "Currency" }, { key: "scope_text", label: "Scope", kind: "textarea" }]; return <div key={metric.id} className="flex items-start justify-between gap-3 rounded-2xl bg-[#FFF3F4] p-4"><div><p className="text-lg font-semibold text-[#A73D52]">{formatMetric(metric)}</p><p className="mt-1 text-sm leading-5 text-[#64748B]">{accomplishment?.statement}</p></div><CareerFactEditor compact entityType="metric" recordId={metric.id} title="Quantified evidence" fields={metricFields} initialValues={{ accomplishment_id: metric.accomplishment_id, metric_type: metric.metric_type, value_numeric: metric.value_numeric, value_text: metric.value_text, before_numeric: metric.before_numeric, before_text: metric.before_text, after_numeric: metric.after_numeric, after_text: metric.after_text, unit: metric.unit, currency: metric.currency, scope_text: metric.scope_text }} /></div>; })}</div></section>
        </div>
      </div>

      <footer className="mt-8 rounded-3xl border border-[#E8E2E3] bg-[#183A5A] p-6 text-white"><div className="flex items-start gap-3"><BadgeCheck className="mt-0.5 size-5 shrink-0 text-[#F3A0A0]" /><div className="min-w-0 grow"><h2 className="font-semibold">Provenance & immutable fact versions</h2><p className="mt-2 text-sm leading-6 text-white/65">This owner-editable profile is backed by {sourcesResult.data?.length ?? 0} reviewed sources and {provenance.length} field-level provenance records. KF Resume controls employment dates and exact titles; owner-confirmed resolutions control education, client context, project canonicalization, and current credential status. New extraction can suggest a change but cannot silently overwrite an owner-confirmed fact.</p>
        <div className="mt-5 grid gap-3 lg:grid-cols-2"><details id="provenance" className="rounded-2xl bg-white/8 p-4"><summary className="cursor-pointer text-sm font-semibold text-white">Open provenance · {provenance.length + factSources.length} records</summary><div className="mt-4 max-h-[32rem] space-y-3 overflow-y-auto pr-1">{factSources.map((source) => { const fact = factsById.get(source.career_fact_id); return <article key={source.id} className="rounded-xl bg-white/8 p-3 text-xs leading-5 text-white/70"><p className="font-semibold text-white">{fact ? displayFactValue(fact.current_value) : "Authoritative fact"}</p><p>{source.career_sources?.label ?? "Reviewed source"} · {source.confirmation_method.replaceAll("_", " ").toLowerCase()}</p><p>{source.source_reference}</p><p>First added {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(source.first_added_at))} · Updated {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(source.last_changed_at))}</p></article>; })}{provenance.map((entry) => <article key={entry.id} className="rounded-xl bg-white/8 p-3 text-xs leading-5 text-white/70"><p className="font-semibold text-white">{entry.entity_type.replaceAll("_", " ")} · {entry.field_name.replaceAll("_", " ")}</p><p>{entry.career_sources?.label ?? "Reviewed source"}{entry.source_page > 0 ? ` · page ${entry.source_page}` : ""} · {entry.source_role.toLowerCase()}</p><p className="break-words">{entry.source_wording}</p>{entry.resolution_note && <p className="text-[#F6C4CC]">{entry.resolution_note}</p>}<p>First added {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(entry.created_at))} · Updated {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(entry.updated_at))}</p></article>)}</div></details>
          <details id="version-history" className="rounded-2xl bg-white/8 p-4"><summary className="cursor-pointer text-sm font-semibold text-white">Open version history · latest {factVersions.length}</summary>{factVersions.length > 0 && <ul className="mt-4 max-h-[32rem] space-y-2 overflow-y-auto pr-1">{factVersions.map((entry) => <li key={entry.id} className="min-w-0 rounded-xl bg-white/8 px-4 py-3 text-xs text-white/70"><span className="font-semibold text-white">Version {entry.version_number}</span> · {entry.change_source.replaceAll("_", " ").toLowerCase()}<br /><span className="break-words">{entry.previous_value === null ? "Initial fact" : `${displayFactValue(entry.previous_value)} → ${displayFactValue(entry.new_value)}`}</span>{entry.reason && <><br />{entry.reason}</>}<br />{new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(new Date(entry.changed_at))}</li>)}</ul>}</details></div>{(historyResult.data?.length ?? 0) > 0 && <p className="mt-4 text-xs text-white/50">Normalized record history also retains {historyResult.data?.length} recent owner/import changes.</p>}</div></div></footer>
    </div>
  </AppShell>;
}
